
- defaults:
    link:
        create: true
        relink: true
- yay:
    - autorandr
    - bauerbill
    - fasd
    - fd
    - fpp-git
    - fzf
    - galnces
    - pianobar
    - powerpill
    - ripgrep
    - terminte
    - topgrade

- link:
    ~/.config/autorandr:
    ~/.config/bauerbill:
    ~/.config/fontconfig:
    ~/.config/pianobar/config:
        path: pianobar/config
        create: true
        relink: true
    ~/.config/powerpill:
    ~/.config/termite:
    ~/.config/topgrade.toml:
    ~/.config/yay:
