
- defaults:
    link:
        create: true
        relink: true
- pacaur:
    - fzf
    - fd-rs
    - fpp-git

- link:
    ~/.config/autorandr:
    ~/.config/bauerbill:
    ~/.config/fontconfig:
    ~/.config/pacaur:
    ~/.config/pianobar/config:
        path: pianobar/config
        create: true
        relink: true
    ~/.config/powerpill:
    ~/.config/termite:
    ~/.config/yaourt:
