- clean:
    ~/.ideavimrc:
      force: true
    ~/.local/share/bin:
      force: true

- defaults:
    link:
      relink: true
      create: true

- link:
    ~/.ideavimrc:
      force: true

- shell:
    - ["ln -s /usr/bin/intellij-idea-ultimate-edition ${XDG_DATA_HOME}/bin/idea", simple bin name]
    #- ["ln -s /usr/bin/idea-ce-eap ${XDG_DATA_HOME}/bin/idea", simple bin name]
    #- ["ln -s /usr/bin/pycharm-eap ${XDG_DATA_HOME}/bin/pycharm", just link to idea]

- pacaur:
  # professional
  - intellij-idea-ultimate-edition-jre
  - intellij-idea-ultimate-edition
  - pycharm-professional
  # community
  #- intellij-jdk
  #- intellij-idea-ce-eap
  #- pycharm-community-eap
