- clean:
    ~/.ideavimrc:
      force: true
    ~/.local/share/bin:
      force: true

- defaults:
    link:
      relink: true
      create: true

- link:
    ~/.ideavimrc:
      force: true

- shell:
    - ["ln -s /usr/bin/intellij-idea-ultimate-edition ${XDG_DATA_HOME}/bin/idea", just link to idea]

- pacaur:
  - intellij-idea-ultimate-edition-jre
  - intellij-idea-ultimate-edition
  - pycharm-professional
