
- defaults:
    link:
        relink: true

- link:
    ~/.zprofile: zsh/zprofile
    ~/.zshenv: zsh/zshenv
    ~/.zshrc: zsh/zshrc

- shell:
    - ["touch ~/.zshrc.local", create .zshrc.local if not exists]

