#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
  xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
  xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
  xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# remove annoing beep
xset -b
setterm -blength 0

# Start GNOME Keyring (without SSH and GPG!)
if [ -f /usr/bin/gnome-keyring-daemon ]; then
    eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets)
    export SSH_AUTH_SOCK
fi

# Reading default variables for X apps
xrdb -merge ~/.Xdefaults

# gnome-keyring
#eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
#export SSH_AUTH_SOCK

function __launch_awesome {
    # so awesome execute command uses aliases
    # (with display manager exit /etc/X11/Xsession.d)
    #source ~/.config/zsh/plugin/core/core.plugin.zsh
    #source ~/.config/zsh/plugin/autorandr/autorandr.plugin.zsh

    # monitors detect
    #autorandr -c &
    dex -a &
    xss-lock -- sxlock -l -f '-misc-inconsolata-medium-r-normal--20-0-0-0-m-0-iso8859-2' &
    #redshift-gtk &

    # start awesome window manager
    exec awesome >> ~/.cache/awesome/stdout 2>> ~/.cache/awesome/stderr
}

function __launch_i3 {
  exec i3
}

session=${1:-awesome}

case "$session" in
    awesome)    __launch_awesome;;
    i3)         __launch_i3;;
    # No known session, try to run it as command
    *)          exec $1;;
esac
